story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story5.urls')),
    path('story1/', include('storynyaraissa.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story5/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'story5'

urlpatterns = [
    path('', views.home, name='home'),
    path('story/', views.story, name='story'),
    path('tambah/', views.agenda, name= 'tambah'),
    path('tambah/data', views.agenda, name= 'tambah'),
    path('jadwal/', views.data, name= 'jadwal'),
    path('jadwal/submit', views.data, name= 'jadwal'),
    path('jadwal/<int:index>', views.detail, name="detail"),
]


story7/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'story7'

urlpatterns = [
    path('accord/', views.accord, name= 'accord'),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'story8'

urlpatterns = [
    path('bookcatalogue', views.bookcatalogue, name= 'book'),
    path('getData', views.getdata),
]
 

storynyaraissa/urls.py
from django.urls import path
from . import views

app_name = 'storynyaraissa'

urlpatterns = [
    path('story1', views.story1, name='story1'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('contact', views.contact, name='contact'),
    # dilanjutkan ...
]

story5/models.py
from django.forms import ModelForm, Textarea
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

SEMESTER_CHOICES = ( 
    ("Gasal 2020/2021", "Gasal 2020/2021"),
    ("Genap 2019/2020", "Genap 2019/2020"), 
    ("Gasal 2019/2020", "Gasal 2019/2020"),
) 

class user(models.Model):
    matkul = models.CharField('Mata Kuliah', max_length=120, null=True)
    sks = models.IntegerField('Jumlah SKS', default=1,
        validators=[
                MaxValueValidator(8),
                MinValueValidator(1)
            ]
        )

    dosen = models.CharField('Dosen', max_length=120, blank=True)
    desc = models.TextField('Deskripsi', max_length=100, null=True)
    semester = models.CharField('Semester', 
        max_length=120, null=True,
        choices = SEMESTER_CHOICES, 
        default = 'Gasal 2020/2021'
        )  

    ruang = models.CharField('Ruang Kelas', max_length=120, blank=True, default='Online Class')

    def __str__(self):
            return f'{self.matkul}'


    class Meta:
        db_table = "user"

story5/forms.py
from django.core import validators
from django import forms

from .models import user

class jadwalform(forms.ModelForm):
    required_css_class = "required"
    class Meta:
        model = user
        fields = ['id','matkul', 'dosen','sks','semester','ruang','desc']
        widgets ={
            'matkul' : forms.TextInput(attrs={'class': 'form-control'}),
            'dosen' : forms.TextInput(attrs={'class': 'form-control'}),
            'sks' : forms.TextInput(attrs={'class': 'form-control'}),
            'semester' : forms.TextInput(attrs={'class': 'form-control'}),
            'ruang' : forms.TextInput(attrs={'class': 'form-control'}),
            'desc' : forms.TextInput(attrs={'class': 'form-control'}),
        }
        

story5/views.py
from django.shortcuts import render, redirect
from .forms import jadwalform
from .models import user


from django.http import HttpResponseRedirect
# Create your views here.
def home(request):
    return render(request, 'story5.html')
def story(request):
    return render(request, 'story.html')

def forms(request):
    return render(request, 'agenda.html')

def agenda(request):
    form = jadwalform(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/tambah')
    else:
        return render(request, 'agenda.html', {'form': form})

def data(request):
    if request.method =="POST":
        stud = user.objects.all()
        user.objects.get(id=request.POST['id']).delete() 
        return HttpResponseRedirect ('/jadwal') 
    else:
        stud = user.objects.all()
        return render(request,'data.html',{'stud' : stud})

def detail(request, index):
        st = user.objects.get(pk=index)
        return render(request, 'list.html', {'st': st})

    





story5/templates/agenda.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}


<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center">
    <form class="col-12" method="POST" action="data" style="margin-top: 150px;">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Submit" class="btn btn-success">
    </form>   
  </div>
  
</div>

{% endblock %}

story5/templates/data.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}

<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center">
    {% if stud %}
    <table class="table" style="margin-top: 150px;">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Dosen</th>
            <th scope="col">Jumlah SKS</th>
            <th scope="col">Semester</th>
            <th scope="col">Ruang kelas</th>
            <th scope="col">Deskripsi</th>
          </tr>
        </thead>
        <tbody>
          {% csrf_token %}
          {% for st in stud %}
            <tr>
              <th scope="row"><a href="{{ st.id }}">{{st.matkul}}</a></th>
              <td >{{st.dosen}}</td>
              <td >{{st.sks}}</td>
              <td >{{st.semester}}</td>
              <td >{{st.ruang}}</td>
              <td >{{st.desc}}</td>
              <td>
                <form action="" method="POST" class="d-inline">
                  {% csrf_token %}
                  <input name="id" value="{{st.id}}" type="hidden">
                  <button type="submit" value="Submit" class="btn btn-primary">Delete</button>
                </form>

                </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
        <h4 class = "text-center alert alert warning">No Records</h4>
    {% endif %}
  </div>
  </div>
{% endblock %}

story5/templates/list.html
{% extends 'base_template.html' %}
{% load static %}

{% block content %}

<div class="main">
  <div class="row h-100 justify-content-center align-items-center">
  <h3 style="margin-top:20px; align-items: center;"> Matkul : {{ std.matkul }} </h3>
</div>
  <div class="row h-100 justify-content-center align-items-center">
  
  <table class="table " style="width:50vw; margin-top: 30px;">
    <tbody>
        <tr>
            <td> Dosen </td>
            <td> {{ st.dosen }} </td>
        </tr>

        <tr>
            <td> Jumlah SKS </td>
            <td> {{ st.sks }} </td>
        </tr>

        <tr>
          <td> Semester </td>
          <td> {{ st.semester }} </td>
      </tr>

        <tr>
          <td> Ruang Kelas </td>
          <td> {{ st.ruang }} </td>
      </tr>

      <tr>
        <td> Deskripsi </td>
        <td> {{ st.desc }} </td>
    </tr>

    </tbody>
</table>
</div>


  {% endblock content %}

story5/templates/story.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}

<style>
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
      text-align: center;
      background-color: #ffff;
    }
    .card:hover {
      box-shadow: 0 8px 16px 0 #28479A;
  }

  </style>

    <section id="story-card" style=" width: 100%; height: auto; box-sizing: border-box; padding: 100px; overflow-x:hidden;">
    <div class="row">
        <div class="col-md">
        <div class="col-lg-6">
        <div class="card" style="width: 25rem;">
            <img class="card-img-top" src="{% static 'image/story1-1.svg' %}" alt="Card image cap">
            <div class="card-body">
            <a href="{% url 'storynyaraissa:story1' %}" class="btn btn-outline-danger" style="background-color:white; font-family: 'Varela Round', sans-serif; color: #E84F3F; font-size: 20px; outline-color: #E84F3F;">Find out more!</a>
            </div>
        </div>
        </div>
        </div>

        <div class="col-md">
          <div class="col-lg-6">
          <div class="card" style="width: 25rem;">
              <img class="card-img-top" src="{% static 'image/story7.svg' %}" alt="Card image cap">
              <div class="card-body">
              <a href="{% url 'story7:accord' %}" class="btn btn-outline-danger" style="background-color:white; font-family: 'Varela Round', sans-serif; color: #E84F3F; font-size: 20px; outline-color: #E84F3F;">Find out more!</a>
              </div>
          </div>
          </div>
          </div>

    </div>
    </section>

    <section id="story-card" style=" width: 100%; height: auto; box-sizing: border-box; padding: 100px; overflow-x:hidden;">
    <div class="row">
    <div class="col-md">
      <div class="col-lg-6">
      <div class="card" style="width: 25rem;">
          <img class="card-img-top" src="{% static 'image/story8.svg' %}" alt="Card image cap">
          <div class="card-body">
          <a href="{% url 'story8:book' %}" class="btn btn-outline-danger" style="background-color:white; font-family: 'Varela Round', sans-serif; color: #E84F3F; font-size: 20px; outline-color: #E84F3F;">Find out more!</a>
          </div>
      </div>
      </div>
      </div>
    </div>
  </section>
{% endblock %}



story5/templates/story5.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <section id="home">
        <div class="main" class="col-lg-12">
            <a hresf = "#"><img src="{% static 'image/hello.png' %}"alt="My Image" class="img-responsive center-block d-block mx-auto" style=" width:540px; height: 480px;"></a>
        </div>
    </section>

    <section id="main" style=" width: 100%; height: auto; min-height: 850px; box-sizing: border-box; background-color: #28479A ; padding: 100px; overflow-x:hidden;">
        <div class="row">
            <div class="col-md">
            <div class="col-lg-6">
              <h1 class= "font-weight-bold title2" style="margin-top: 80px; margin-left: 60px; font-family: 'Varela Round', sans-serif; color: #E84F3F; font-size: 40px;">About me.</h1>
            <div class="col-lg-11">
              <div class="about" style="color: white;"><p class="lead" style="margin-left: 60px; font-size: 26px; font-family: 'Varela Round', sans-serif;">My name is Raissa Naila Thahira. My student id is 1906400236. I'm a second year Computer Science student at University of Indonesia.</p></div>
            <h1 class= "font-weight-bold title2" style=" margin-left: 40px; margin-top: 50px; font-family: 'Varela Round', sans-serif; color: #E84F3F; font-size: 40px;">Education</h1>
            <ul>
                <li style="margin-left: 60px; font-size: 26px; font-family: 'Varela Round', sans-serif; color: white; letter-spacing: 1px;">Universitas Indonesia <br> 2019 - Present</br></li>
                <li style="margin-left: 60px; font-size: 26px; font-family: 'Varela Round', sans-serif; color: white; letter-spacing: 0.5px;">SMA Negeri 1 Pontianak <br> 2016 - 2019</br></li>
            </ul>
            </div>
            </div>
            </div>
        </div>
    </section>
    {% endblock %}