story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story5.urls')),
    path('story1/', include('storynyaraissa.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story5/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'story5'

urlpatterns = [
    path('', views.home, name='home'),
    path('story/', views.story, name='story'),
    path('tambah/', views.agenda, name= 'tambah'),
    path('tambah/data', views.agenda, name= 'tambah'),
    path('jadwal/', views.data, name= 'jadwal'),
    path('jadwal/submit', views.data, name= 'jadwal'),
    path('jadwal/<int:index>', views.detail, name="detail"),
]


story6/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'story6'

urlpatterns = [
    path('kegiatan/', views.acts, name= 'kegiatan'),
    path('kegiatan/data', views.acts, name= 'kegiatan'),
    path('daftar/', views.datact, name="daftar" ),
    path('daftar/data', views.datact, name="daftar" ),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('regist', views.register, name='register'),
    path('login', views.inF, name='login'),
    path('logout', views.outF, name='logout'),
    path('loha', views.loha, name='loha')
]

templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <!-- Bootstrap CSS -->
    <link rel="icon" href="{% static 'images/clown-2.svg' %}"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles1.css' %}"/>
    <title>Raissa Naila Thahira</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'story5:home' %}"><img src="{% static 'image/clown-2.svg' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="container">
            <div class="row justify-content-end">
                <div class="col-4">
            <ul class="navbar-nav" >
              <li class="nav-item active" >
                <a class="nav-link " href="{% url 'story5:home' %}"><h3 class= "font-weight-bold" style="color: #28479A; font-family: 'Varela Round', sans-serif; font-size: 20px;" >Home </h3> <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'story5:story' %}"><h3 class= "font-weight-bold" style="color: #28479A; font-family: 'Varela Round', sans-serif; font-size: 20px">Story </h3> <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <div class="dropdown" >
                    <button class="btn btn-secondary dropdown-toggle shadow-none" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: transparent; border-style: none;" >
                        <h3 class= "font-weight-bold" style="color: #28479A; font-family: 'Varela Round', sans-serif; font-size: 20px">Agenda</h3>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="border: none; border-radius: 0; box-shadow: none;" >
                    <a class="dropdown-item" style="font-size: 12px; color: #E84F3F; font-family: 'Varela Round', sans-serif; background-color: transparent; border-style: none; background-color: white;" href="{% url 'story5:tambah' %}"><h5 class= "font-weight-bold">Tambah</h5></a>
                    <a class="dropdown-item" style="font-size: 12px; color: #E84F3F; font-family: 'Varela Round', sans-serif; background-color: transparent; border-style: none; background-color: white;" href="{% url 'story5:jadwal' %}"><h5 class= "font-weight-bold">jadwal</h5></a>
                    </div>
                </div>
              </li> 
              <li class="nav-item active">
                <div class="dropdown " >
                    <button class="btn btn-secondary dropdown-toggle shadow-none" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: transparent; border-style: none;" >
                        <h3 class= "font-weight-bold" style="color: #28479A; font-family: 'Varela Round', sans-serif; font-size: 20px">Kegiatan</h3>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="border: none; border-radius: 0; box-shadow: none;" >
                    <a class="dropdown-item" style="font-size: 12px; color: #E84F3F; font-family: 'Varela Round', sans-serif; background-color: transparent; border-style: none; background-color: white;" href="{% url 'story6:kegiatan' %}"><h5 class= "font-weight-bold">Tambah Kegiatan</h5></a>
                    <a class="dropdown-item" style="font-size: 12px; color: #E84F3F; font-family: 'Varela Round', sans-serif; background-color: transparent; border-style: none; background-color: white;" href="{% url 'story6:daftar' %}"><h5 class= "font-weight-bold">Daftar Kegiatan</h5></a>
                    </div>
                </div>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'story9:login' %}"><h3 class= "font-weight-bold" style="color: #28479A; font-family: 'Varela Round', sans-serif; font-size: 20px">Login </h3> <span class="sr-only">(current)</span></a>
              </li>

            </ul>
        </div>
        </div>
        </div>
        </div>
    </nav>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% block content %}
{% endblock %}
</body>
</html>