story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story5.urls')),
    path('story1/', include('storynyaraissa.urls')),
    path('', include('story6.urls')),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

story9/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('regist', views.register, name='register'),
    path('login', views.inF, name='login'),
    path('logout', views.outF, name='logout'),
    path('loha', views.loha, name='loha')
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required



# Create your views here.

def loha(request):
    return render(request, "lohalo.html")

def register(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('/loha')
    else:
        form = UserCreationForm()
    return render (request,'regist.html', {'form': form})

def inF(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('/loha')
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {'form': form})

def outF(request):
    logout(request)
    return redirect('/')

story9/templates/login.html
{% extends 'base_acc.html' %}
{% load static %}
{% block content %}
<style>
body {
  background-color:white;
}

html {
    overflow-x: hidden;
}

#title {
    margin-top: 5vh;
    margin-bottom: 5vh;
}

#title h3 {
    font-size:6em;
    font-weight: 800;
    color: #2335A4;
}

.login-section{
    width: 450px;
    padding: 3% 0 0;
    margin: auto;
}

.login-form input{
    font-family: 'Varela Round', sans-serif; 
    outline: none;
    width: 80%;
    border: none;
    font-size: 14px;
    background:#f2f2f2;
    padding: 30px;
    margin: 30px 30px 30px;
    text-align: center;

}

.messages{
    font-size: 10px;
    text-align: center;
    color: #2335A4;
}



</style>

  {% if user.is_authenticated %}
    <section id="login" class="text-center section">
      <h3>yeayy dah masukkk :)))</h3>
      <p>mau keluarrr</p>
      <a href="{% url 'story9:logout' %}">
          <button class="btn btn-primary active" id="logout">Logout</button>
      </a>
    </section>
  
  {% else %}
    <section id="title" class="text-center section">
      <h3>Login</h3>
    </section>

    <section style = "height: 100vh;"> 
        <div class="login-section">
            <div class="login-form">
                <form method="POST" action="{% url 'story9:login' %}">
                {% csrf_token %}
                {{form.as_table}}  
                <input type="submit" name = "create" value = "login">
                </form>
                <p> kalo mau sign up</p>
                <p> <a href="{% url 'story9:register' %}">disini</a> </p>

            </div>
        </div>
    </section>
{% endif %}
{% endblock content %}

story9/templates/lohalo.html
{% extends 'base_acc.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}
    <section class="text-center section">
        <h3>lohalohaloo {{ user }}</h3>
        <p>mau keluarrr ???</p>
        <a href="{% url 'story9:logout' %}">
            <button class="btn btn-primary active" id="logout">Logout</button>
        </a>
    </section>

{% else %}
    <section id="login" class="text-center section">
        <h3>ehh login duluu</h3>
        <a href="{% url 'story9:login' %}">
            <button class="btn btn-primary active" id="logout">Login</button>
        </a>
    </section>

{% endif %}
{% endblock content %}

story9/templates/regist.html
{% extends 'base_acc.html' %}
{% load static %}
{% block content %}
<style>

    body {
      background-color:white;
    }
    
    html {
        overflow-x: hidden;
    }
    
    #title {
        margin-top: 5vh;
        margin-bottom: 5vh;
    }
    
    #title h3 {
        font-size:6em;
        font-weight: 800;
        color: #2335A4;
    }

    .login-section{
        width: 450px;
        padding: 3% 0 0;
        margin: auto;
    }
    
    .login-form input{
        font-family: 'Varela Round', sans-serif; 
        outline: none;
        width: 80%;
        border: none;
        font-size: 14px;
        background:#f2f2f2;
        padding: 30px;
        margin: 30px 30px 30px;
        text-align: center;
    
    }

    .messages{
        font-size: 10px;
        text-align: center;
        color: #2335A4;
    }



</style>

    {% if user.is_authenticated %}
        <section id="login" class="text-center section">
            <h3>yeayy dah masukkk :)))</h3>
            <p>mau keluarrr</p>
            <a href="{% url 'story9:logout' %}">
                <button class="btn btn-primary active" id="logout">Logout</button>
            </a>
        </section>

    {% else %}
        <section id="title" class="text-center section">
            <h3>Sign Up</h3>
        </section>

        <section style = "height: 100vh;"> 
            <div class="login-section">
                <div class="login-form">
                    <form method="POST" action="">
                    {% csrf_token %}
                    {{form.as_table}}  
                    <input type="submit" name = "create" value = "login">
                    <p> login <a href="{% url 'story9:login' %}">here</a> </p>
                    </form>
                </div>
            </div>
        </section>
    {% endif %}
{% endblock %}